[package]
name = "jaro_winkler_distance"
version = "0.1.1"
edition = "2021"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "jarowinkler_bench"
harness = false
